export const CustomTypography = {
  'subHeader-regular': {
    fontFamily: 'sans-serif',
    fontSize: '24px',
    lineHeight: '132%',
    fontKerning: '0%',
    fontWeight: 400,
  },
  'subHeader-bold': {
    fontFamily: 'sans-serif',
    fontSize: '24px',
    lineHeight: '132%',
    fontKerning: '0%',
    fontWeight: 700,
  },
  'p-lg-regular': {
    fontFamily: 'sans-serif',
    fontSize: '18px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 400,
  },
  'p-lg-bold': {
    fontFamily: 'sans-serif',
    fontSize: '18px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 700,
  },
  'p-md-regular': {
    fontFamily: 'sans-serif',
    fontSize: '16px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 400,
  },
  'p-md-bold': {
    fontFamily: 'sans-serif',
    fontSize: '16px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 700,
  },
  'p-sm-regular': {
    fontFamily: 'sans-serif',
    fontSize: '12px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 400,
  },
  'p-xs-regular': {
    fontFamily: 'sans-serif',
    fontSize: '12px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 300,
  },
  'label-lg-bold': {
    fontFamily: 'sans-serif',
    fontSize: '18px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 700,
  },
  'label-md-bold': {
    fontFamily: 'sans-serif',
    fontSize: '14px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 700,
  },
  'label-md-regular': {
    fontFamily: 'sans-serif',
    fontSize: '14px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 400,
  },
  'label-sm-regular': {
    fontFamily: 'sans-serif',
    fontSize: '12px',
    lineHeight: '100%',
    fontKerning: '0%',
    fontWeight: 400,
  },
};
